import { MigrationInterface, QueryRunner } from "typeorm";

export class InitDB1779628818676 implements MigrationInterface {
    name = 'InitDB1779628818676'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "planet_images" ("id" SERIAL NOT NULL, "filename" character varying NOT NULL, "original-name" character varying NOT NULL, "planetId" integer, CONSTRAINT "PK_2da35f1a91cd6a817b8bee36ec9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "planets" ("id" integer NOT NULL, "name" character varying, "rotation_period" character varying, "orbital_period" character varying, "diameter" character varying, "climate" character varying, "gravity" character varying, "terrain" character varying, "surface_water" character varying, "population" character varying, "url" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "edited_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_d5fbc2513a6d4909fe31938b0fd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "starship_images" ("id" SERIAL NOT NULL, "filename" character varying NOT NULL, "original-name" character varying NOT NULL, "starshipId" integer, CONSTRAINT "PK_e3004f5ef8d26cf1dec69e6cafe" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "starships" ("id" integer NOT NULL, "name" character varying, "model" character varying, "manufacturer" character varying, "cost_in_credits" character varying, "length" character varying, "max_atmosphering_speed" character varying, "crew" character varying, "passengers" character varying, "cargo_capacity" character varying, "consumables" character varying, "hyperdrive_rating" character varying, "MGLT" character varying, "starship_class" character varying, "url" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "edited_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_10c86d0ac9be05d3f986287a092" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "species_images" ("id" SERIAL NOT NULL, "filename" character varying NOT NULL, "original-name" character varying NOT NULL, "speciesId" integer, CONSTRAINT "PK_4ed933fe5bc4c4f196b44602b27" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "species" ("id" integer NOT NULL, "name" character varying, "classification" character varying, "designation" character varying, "average_height" character varying, "skin_colors" character varying, "hair_colors" character varying, "eye_colors" character varying, "average_lifespan" character varying, "language" character varying, "url" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "edited_at" TIMESTAMP NOT NULL DEFAULT now(), "homeworld_id" integer, CONSTRAINT "PK_ae6a87f2423ba6c25dc43c32770" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "film_images" ("id" SERIAL NOT NULL, "filename" character varying NOT NULL, "original-name" character varying NOT NULL, "filmId" integer, CONSTRAINT "PK_6f51ee7b1057b05eda6e4b94f4c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "films" ("id" integer NOT NULL, "title" character varying, "episode_id" integer, "opening_crawl" text, "director" character varying, "producer" character varying, "release_date" character varying, "url" character varying NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "edited_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_697487ada088902377482c970d1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "people_images" ("id" SERIAL NOT NULL, "filename" character varying NOT NULL, "original-name" character varying NOT NULL, "characterId" integer, CONSTRAINT "PK_0a4d9b7dad67c358432b4aea3ce" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "characters" ("id" integer NOT NULL, "name" character varying, "height" character varying, "mass" character varying, "hair_color" character varying, "skin_color" character varying, "eye_color" character varying, "birth_year" character varying, "gender" character varying, "url" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "edited_at" TIMESTAMP NOT NULL DEFAULT now(), "homeworld_id" integer, CONSTRAINT "PK_9d731e05758f26b9315dac5e378" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "vehicle_images" ("id" SERIAL NOT NULL, "filename" character varying NOT NULL, "original-name" character varying NOT NULL, "vehicleId" integer, CONSTRAINT "PK_62a037bce2dae7af30fc41cc984" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "vehicles" ("id" integer NOT NULL, "name" character varying, "model" character varying, "manufacturer" character varying, "cost_in_credits" character varying, "length" character varying, "max_atmosphering_speed" character varying, "crew" character varying, "passengers" character varying, "cargo_capacity" character varying, "consumables" character varying, "vehicle_class" character varying, "url" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "edited_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_18d8646b59304dce4af3a9e35b6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "films_characters" ("filmsId" integer NOT NULL, "charactersId" integer NOT NULL, CONSTRAINT "PK_3a0d6f0e5a989cdf194360925a1" PRIMARY KEY ("filmsId", "charactersId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b6074bc36d62dd97fe2b915d35" ON "films_characters" ("filmsId") `);
        await queryRunner.query(`CREATE INDEX "IDX_aab95cc3bdd164b4d2c95b7e9d" ON "films_characters" ("charactersId") `);
        await queryRunner.query(`CREATE TABLE "films_planets" ("filmsId" integer NOT NULL, "planetsId" integer NOT NULL, CONSTRAINT "PK_01f59c5538e47ddf0d5cb08922c" PRIMARY KEY ("filmsId", "planetsId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a8db04b134255125a4a990c656" ON "films_planets" ("filmsId") `);
        await queryRunner.query(`CREATE INDEX "IDX_56eec3c43f5246c6a26f4e61d8" ON "films_planets" ("planetsId") `);
        await queryRunner.query(`CREATE TABLE "films_starships" ("filmsId" integer NOT NULL, "starshipsId" integer NOT NULL, CONSTRAINT "PK_9586ceeb5fb2a092f37d3eb9ec1" PRIMARY KEY ("filmsId", "starshipsId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c6ae67fefde29efc7325b74baa" ON "films_starships" ("filmsId") `);
        await queryRunner.query(`CREATE INDEX "IDX_98904c9cab6a9c3c11aeacf768" ON "films_starships" ("starshipsId") `);
        await queryRunner.query(`CREATE TABLE "films_vehicles" ("filmsId" integer NOT NULL, "vehiclesId" integer NOT NULL, CONSTRAINT "PK_e7b85e74e590a5e6449fac7313a" PRIMARY KEY ("filmsId", "vehiclesId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d892418f6e02d0ebce56bd3580" ON "films_vehicles" ("filmsId") `);
        await queryRunner.query(`CREATE INDEX "IDX_4465b1c1a89520616f3c6ccad7" ON "films_vehicles" ("vehiclesId") `);
        await queryRunner.query(`CREATE TABLE "films_species" ("filmsId" integer NOT NULL, "speciesId" integer NOT NULL, CONSTRAINT "PK_ee6ab031d5d0eec079b6a352b7f" PRIMARY KEY ("filmsId", "speciesId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_30663fc8495f09199efa33ab85" ON "films_species" ("filmsId") `);
        await queryRunner.query(`CREATE INDEX "IDX_b5b68c8f3779bcdaa9afda0378" ON "films_species" ("speciesId") `);
        await queryRunner.query(`CREATE TABLE "characters_vehicles" ("charactersId" integer NOT NULL, "vehiclesId" integer NOT NULL, CONSTRAINT "PK_f7ac3d46e51dbc3665312af8680" PRIMARY KEY ("charactersId", "vehiclesId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_fa6c904dcd86ae24e237f30916" ON "characters_vehicles" ("charactersId") `);
        await queryRunner.query(`CREATE INDEX "IDX_422ca902043af1d215fae69b20" ON "characters_vehicles" ("vehiclesId") `);
        await queryRunner.query(`CREATE TABLE "characters_starships" ("charactersId" integer NOT NULL, "starshipsId" integer NOT NULL, CONSTRAINT "PK_b55b3628dc27534fb02c1c89d61" PRIMARY KEY ("charactersId", "starshipsId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_7a8145d30c74e83487d1f7088f" ON "characters_starships" ("charactersId") `);
        await queryRunner.query(`CREATE INDEX "IDX_a2fa3f2050b847e2f0f42ac1fb" ON "characters_starships" ("starshipsId") `);
        await queryRunner.query(`CREATE TABLE "characters_species" ("charactersId" integer NOT NULL, "speciesId" integer NOT NULL, CONSTRAINT "PK_6204eae0a400ff50339879a0736" PRIMARY KEY ("charactersId", "speciesId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_3917734056cb6e7dcfd66e8163" ON "characters_species" ("charactersId") `);
        await queryRunner.query(`CREATE INDEX "IDX_a8bd10be950b26aa885088e165" ON "characters_species" ("speciesId") `);
        await queryRunner.query(`ALTER TABLE "planet_images" ADD CONSTRAINT "FK_7c99a676f3b67212e8d1b4dbf17" FOREIGN KEY ("planetId") REFERENCES "planets"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "starship_images" ADD CONSTRAINT "FK_7267ec6c7a51e3e3685475470a7" FOREIGN KEY ("starshipId") REFERENCES "starships"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "species_images" ADD CONSTRAINT "FK_cf6be92eb6716cc451c736badb1" FOREIGN KEY ("speciesId") REFERENCES "species"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "species" ADD CONSTRAINT "FK_f7e93a1974cc86fd87ce6777319" FOREIGN KEY ("homeworld_id") REFERENCES "planets"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "film_images" ADD CONSTRAINT "FK_1e505ef4f3d6a2d9aabd6acb54d" FOREIGN KEY ("filmId") REFERENCES "films"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "people_images" ADD CONSTRAINT "FK_1946e2a4a6f2ce1f8537e1816d5" FOREIGN KEY ("characterId") REFERENCES "characters"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "characters" ADD CONSTRAINT "FK_91fc27446e66aadf01721cc0da8" FOREIGN KEY ("homeworld_id") REFERENCES "planets"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "vehicle_images" ADD CONSTRAINT "FK_9a907b93045b8793801158fbba2" FOREIGN KEY ("vehicleId") REFERENCES "vehicles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "films_characters" ADD CONSTRAINT "FK_b6074bc36d62dd97fe2b915d356" FOREIGN KEY ("filmsId") REFERENCES "films"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "films_characters" ADD CONSTRAINT "FK_aab95cc3bdd164b4d2c95b7e9d0" FOREIGN KEY ("charactersId") REFERENCES "characters"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "films_planets" ADD CONSTRAINT "FK_a8db04b134255125a4a990c656d" FOREIGN KEY ("filmsId") REFERENCES "films"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "films_planets" ADD CONSTRAINT "FK_56eec3c43f5246c6a26f4e61d81" FOREIGN KEY ("planetsId") REFERENCES "planets"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "films_starships" ADD CONSTRAINT "FK_c6ae67fefde29efc7325b74baa4" FOREIGN KEY ("filmsId") REFERENCES "films"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "films_starships" ADD CONSTRAINT "FK_98904c9cab6a9c3c11aeacf768b" FOREIGN KEY ("starshipsId") REFERENCES "starships"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "films_vehicles" ADD CONSTRAINT "FK_d892418f6e02d0ebce56bd35809" FOREIGN KEY ("filmsId") REFERENCES "films"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "films_vehicles" ADD CONSTRAINT "FK_4465b1c1a89520616f3c6ccad73" FOREIGN KEY ("vehiclesId") REFERENCES "vehicles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "films_species" ADD CONSTRAINT "FK_30663fc8495f09199efa33ab85e" FOREIGN KEY ("filmsId") REFERENCES "films"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "films_species" ADD CONSTRAINT "FK_b5b68c8f3779bcdaa9afda0378e" FOREIGN KEY ("speciesId") REFERENCES "species"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "characters_vehicles" ADD CONSTRAINT "FK_fa6c904dcd86ae24e237f30916b" FOREIGN KEY ("charactersId") REFERENCES "characters"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "characters_vehicles" ADD CONSTRAINT "FK_422ca902043af1d215fae69b204" FOREIGN KEY ("vehiclesId") REFERENCES "vehicles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "characters_starships" ADD CONSTRAINT "FK_7a8145d30c74e83487d1f7088f5" FOREIGN KEY ("charactersId") REFERENCES "characters"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "characters_starships" ADD CONSTRAINT "FK_a2fa3f2050b847e2f0f42ac1fb1" FOREIGN KEY ("starshipsId") REFERENCES "starships"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "characters_species" ADD CONSTRAINT "FK_3917734056cb6e7dcfd66e8163c" FOREIGN KEY ("charactersId") REFERENCES "characters"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "characters_species" ADD CONSTRAINT "FK_a8bd10be950b26aa885088e1656" FOREIGN KEY ("speciesId") REFERENCES "species"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "characters_species" DROP CONSTRAINT "FK_a8bd10be950b26aa885088e1656"`);
        await queryRunner.query(`ALTER TABLE "characters_species" DROP CONSTRAINT "FK_3917734056cb6e7dcfd66e8163c"`);
        await queryRunner.query(`ALTER TABLE "characters_starships" DROP CONSTRAINT "FK_a2fa3f2050b847e2f0f42ac1fb1"`);
        await queryRunner.query(`ALTER TABLE "characters_starships" DROP CONSTRAINT "FK_7a8145d30c74e83487d1f7088f5"`);
        await queryRunner.query(`ALTER TABLE "characters_vehicles" DROP CONSTRAINT "FK_422ca902043af1d215fae69b204"`);
        await queryRunner.query(`ALTER TABLE "characters_vehicles" DROP CONSTRAINT "FK_fa6c904dcd86ae24e237f30916b"`);
        await queryRunner.query(`ALTER TABLE "films_species" DROP CONSTRAINT "FK_b5b68c8f3779bcdaa9afda0378e"`);
        await queryRunner.query(`ALTER TABLE "films_species" DROP CONSTRAINT "FK_30663fc8495f09199efa33ab85e"`);
        await queryRunner.query(`ALTER TABLE "films_vehicles" DROP CONSTRAINT "FK_4465b1c1a89520616f3c6ccad73"`);
        await queryRunner.query(`ALTER TABLE "films_vehicles" DROP CONSTRAINT "FK_d892418f6e02d0ebce56bd35809"`);
        await queryRunner.query(`ALTER TABLE "films_starships" DROP CONSTRAINT "FK_98904c9cab6a9c3c11aeacf768b"`);
        await queryRunner.query(`ALTER TABLE "films_starships" DROP CONSTRAINT "FK_c6ae67fefde29efc7325b74baa4"`);
        await queryRunner.query(`ALTER TABLE "films_planets" DROP CONSTRAINT "FK_56eec3c43f5246c6a26f4e61d81"`);
        await queryRunner.query(`ALTER TABLE "films_planets" DROP CONSTRAINT "FK_a8db04b134255125a4a990c656d"`);
        await queryRunner.query(`ALTER TABLE "films_characters" DROP CONSTRAINT "FK_aab95cc3bdd164b4d2c95b7e9d0"`);
        await queryRunner.query(`ALTER TABLE "films_characters" DROP CONSTRAINT "FK_b6074bc36d62dd97fe2b915d356"`);
        await queryRunner.query(`ALTER TABLE "vehicle_images" DROP CONSTRAINT "FK_9a907b93045b8793801158fbba2"`);
        await queryRunner.query(`ALTER TABLE "characters" DROP CONSTRAINT "FK_91fc27446e66aadf01721cc0da8"`);
        await queryRunner.query(`ALTER TABLE "people_images" DROP CONSTRAINT "FK_1946e2a4a6f2ce1f8537e1816d5"`);
        await queryRunner.query(`ALTER TABLE "film_images" DROP CONSTRAINT "FK_1e505ef4f3d6a2d9aabd6acb54d"`);
        await queryRunner.query(`ALTER TABLE "species" DROP CONSTRAINT "FK_f7e93a1974cc86fd87ce6777319"`);
        await queryRunner.query(`ALTER TABLE "species_images" DROP CONSTRAINT "FK_cf6be92eb6716cc451c736badb1"`);
        await queryRunner.query(`ALTER TABLE "starship_images" DROP CONSTRAINT "FK_7267ec6c7a51e3e3685475470a7"`);
        await queryRunner.query(`ALTER TABLE "planet_images" DROP CONSTRAINT "FK_7c99a676f3b67212e8d1b4dbf17"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a8bd10be950b26aa885088e165"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3917734056cb6e7dcfd66e8163"`);
        await queryRunner.query(`DROP TABLE "characters_species"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a2fa3f2050b847e2f0f42ac1fb"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7a8145d30c74e83487d1f7088f"`);
        await queryRunner.query(`DROP TABLE "characters_starships"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_422ca902043af1d215fae69b20"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fa6c904dcd86ae24e237f30916"`);
        await queryRunner.query(`DROP TABLE "characters_vehicles"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b5b68c8f3779bcdaa9afda0378"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_30663fc8495f09199efa33ab85"`);
        await queryRunner.query(`DROP TABLE "films_species"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4465b1c1a89520616f3c6ccad7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d892418f6e02d0ebce56bd3580"`);
        await queryRunner.query(`DROP TABLE "films_vehicles"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_98904c9cab6a9c3c11aeacf768"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c6ae67fefde29efc7325b74baa"`);
        await queryRunner.query(`DROP TABLE "films_starships"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_56eec3c43f5246c6a26f4e61d8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a8db04b134255125a4a990c656"`);
        await queryRunner.query(`DROP TABLE "films_planets"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_aab95cc3bdd164b4d2c95b7e9d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b6074bc36d62dd97fe2b915d35"`);
        await queryRunner.query(`DROP TABLE "films_characters"`);
        await queryRunner.query(`DROP TABLE "vehicles"`);
        await queryRunner.query(`DROP TABLE "vehicle_images"`);
        await queryRunner.query(`DROP TABLE "characters"`);
        await queryRunner.query(`DROP TABLE "people_images"`);
        await queryRunner.query(`DROP TABLE "films"`);
        await queryRunner.query(`DROP TABLE "film_images"`);
        await queryRunner.query(`DROP TABLE "species"`);
        await queryRunner.query(`DROP TABLE "species_images"`);
        await queryRunner.query(`DROP TABLE "starships"`);
        await queryRunner.query(`DROP TABLE "starship_images"`);
        await queryRunner.query(`DROP TABLE "planets"`);
        await queryRunner.query(`DROP TABLE "planet_images"`);
    }

}
